##===- bindings/ocaml/analysis/Makefile --------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##
# 
# This is the makefile for the Objective Caml Llvm_analysis interface.
# 
##===----------------------------------------------------------------------===##

LEVEL := ../../..
LIBRARYNAME := llvm_analysis_safe
UsedComponents := analysis
UsedOcamlInterfaces := llvm_safe

include ../Makefile.ocaml
